// ============================================================================
// JCE SYSTEM — Purchasing module shared data (Stage 6)
//   PO type Local·Import is the central branch. Derived: payment status,
//   tracker progress. Numbers: PO YYMM#### (local) / YYMM####IC (import).
// ============================================================================

// ---- U2 PO ledger ----------------------------------------------------------
const POS = [
  {
    no: "2605-0188IC",
    type: "Import",
    date: "2026-05-22",
    project: "NORECO II — 13.2KV",
    supplier: "Shenda Electric Co.",
    desc: "Power transformers 10MVA + switchgear",
    amount: 84000,
    ccy: "USD",
    status: "Approved",
    pay: "Downpayment Paid",
    so: "26-05-378",
    mr: "JCE-MR-2026-0142",
    stage: 6,
  },
  {
    no: "2605-0204",
    type: "Local",
    date: "2026-05-29",
    project: "Workshop",
    supplier: "Cebu Steel Corp.",
    desc: "Structural steel & consumables",
    amount: 318450,
    ccy: "PHP",
    status: "Approved",
    pay: "Unpaid",
    so: "WORKSHOP",
    mr: "JCE-MR-2026-0138",
    localStage: 2,
  },
  {
    no: "2605-0201",
    type: "Local",
    date: "2026-05-27",
    project: "Cavite 69KV",
    supplier: "Meralco Industrial",
    desc: "Conductors & accessories",
    amount: 1240000,
    ccy: "PHP",
    status: "Sent",
    pay: "Unpaid",
    so: "26-04-355",
    mr: "JCE-MR-2026-0140",
    localStage: 1,
  },
  {
    no: "2604-0177IC",
    type: "Import",
    date: "2026-04-30",
    project: "Solar Farm Tarlac",
    supplier: "JinkoSolar Intl.",
    desc: "PV modules 550Wp ×9,100",
    amount: 512000,
    ccy: "USD",
    status: "Sent",
    pay: "Fully Paid",
    so: "25-11-290",
    mr: "JCE-MR-2026-0120",
    stage: 14,
  },
  {
    no: "2604-0166",
    type: "Local",
    date: "2026-04-18",
    project: "NORECO II — 13.2KV",
    supplier: "ABB Inc.",
    desc: "Protection relays",
    amount: 86200,
    ccy: "PHP",
    status: "Closed",
    pay: "Fully Paid",
    so: "26-05-378",
    mr: "JCE-MR-2026-0118",
    localStage: 5,
  },
  {
    no: "2606-0210",
    type: "Local",
    date: "2026-06-02",
    project: "Workshop",
    supplier: "Cebu Steel Corp.",
    desc: "Welding consumables",
    amount: 48200,
    ccy: "PHP",
    status: "For Approval",
    pay: "Unpaid",
    so: "WORKSHOP",
    mr: "—",
    localStage: 0,
  },
];
const PO_STATUS_TONE = {
  Draft: "neutral",
  "For Approval": "pending",
  Approved: "info",
  Sent: "info",
  Closed: "success",
  "Cancelled/Void": "danger",
  Void: "danger",
};
const PAY_TONE = {
  Unpaid: "danger",
  "Downpayment Paid": "pending",
  "Fully Paid": "success",
};

// ---- U7 import 15-stage tracker (PO 2605-0188IC) ---------------------------
const IMPORT_STAGES = [
  {
    n: 1,
    name: "BOM",
    owner: "BDD / PMG",
    status: "Done",
    target: "2026-05-10",
    actual: "2026-05-09",
    docs: ["BOM.xlsx"],
  },
  {
    n: 2,
    name: "MR",
    owner: "PMG",
    status: "Done",
    target: "2026-05-12",
    actual: "2026-05-11",
    docs: ["JCE-MR-2026-0142"],
  },
  {
    n: 3,
    name: "PO + Supplier Quotation",
    owner: "Purchasing",
    status: "Done",
    target: "2026-05-20",
    actual: "2026-05-22",
    docs: ["PO-2605-0188IC", "Quote.pdf"],
  },
  {
    n: 4,
    name: "Approval of Sir Jimwel",
    owner: "President",
    status: "Done",
    target: "2026-05-22",
    actual: "2026-05-23",
    gate: true,
    docs: [],
  },
  {
    n: 5,
    name: "Performa Invoice",
    owner: "Supplier",
    status: "Done",
    target: "2026-05-24",
    actual: "2026-05-25",
    docs: ["PI-99821.pdf"],
  },
  {
    n: 6,
    name: "Technical Spec & Drawing",
    owner: "Engineering",
    status: "In Progress",
    target: "2026-06-05",
    actual: "—",
    docs: [],
  },
  {
    n: 7,
    name: "JCE Approval + Downpayment",
    owner: "President / Finance",
    status: "Blocked",
    target: "2026-06-08",
    actual: "—",
    gate: true,
    docs: ["RFP-PUR-26060021 (DP)"],
  },
  {
    n: 8,
    name: "Production",
    owner: "Supplier",
    status: "Pending",
    target: "2026-07-10",
    actual: "—",
    docs: [],
  },
  {
    n: 9,
    name: "Delivery Lead Time",
    owner: "Supplier",
    status: "Pending",
    target: "2026-07-20",
    actual: "—",
    docs: [],
  },
  {
    n: 10,
    name: "Balance Payment",
    owner: "Finance",
    status: "Pending",
    target: "2026-08-01",
    actual: "—",
    docs: [],
  },
  {
    n: 11,
    name: "Shipping Documents",
    owner: "Purchasing",
    status: "Pending",
    target: "2026-08-05",
    actual: "—",
    docs: ["B/L", "Packing List", "Commercial Invoice", "Form E"],
  },
  {
    n: 12,
    name: "Departure",
    owner: "Freight",
    status: "Pending",
    target: "2026-08-08",
    actual: "—",
    docs: [],
  },
  {
    n: 13,
    name: "Arrival",
    owner: "Freight",
    status: "Pending",
    target: "2026-08-22",
    actual: "—",
    docs: [],
  },
  {
    n: 14,
    name: "Customs Clearance",
    owner: "Broker",
    status: "Pending",
    target: "2026-08-25",
    actual: "—",
    docs: [],
  },
  {
    n: 15,
    name: "Delivery Onsite",
    owner: "Warehouse",
    status: "Pending",
    target: "2026-08-28",
    actual: "—",
    docs: ["DR → MRR"],
  },
];
const STAGE_TONE = {
  Done: "success",
  "In Progress": "info",
  Blocked: "danger",
  Pending: "neutral",
};

// ---- U5 RFP register -------------------------------------------------------
const RFPS = [
  {
    no: "RFP-PUR-26060021",
    date: "2026-06-02",
    po: "2605-0188IC",
    supplier: "Shenda Electric Co.",
    project: "NORECO II — 13.2KV",
    type: "Downpayment",
    due: "2026-06-08",
    net: 1764000,
    status: "Verified",
  },
  {
    no: "RFP-PUR-26050188",
    date: "2026-05-30",
    po: "2605-0204",
    supplier: "Cebu Steel Corp.",
    project: "Workshop",
    type: "Single",
    due: "2026-06-15",
    net: 312081,
    status: "Submitted",
  },
  {
    no: "RFP-PUR-26040177",
    date: "2026-04-30",
    po: "2604-0177IC",
    supplier: "JinkoSolar Intl.",
    project: "Solar Farm Tarlac",
    type: "Balance",
    due: "2026-05-20",
    net: 7680000,
    status: "Paid",
  },
];
const RFP_TONE = {
  Draft: "neutral",
  Submitted: "pending",
  Verified: "info",
  "Received (Accounting)": "info",
  Paid: "success",
};

// ---- U9 suppliers ----------------------------------------------------------
const SUPPLIERS = [
  {
    code: "JCE 00012",
    name: "Shenda Electric Co.",
    top: "50/50",
    tin: "—",
    city: "Shenzhen, CN",
    cat: "Transformers & switchgear",
    offers: ["Transformers", "Switchgear"],
    active: true,
    bankPending: true,
  },
  {
    code: "JCE 00007",
    name: "Cebu Steel Corp.",
    top: "NET30",
    tin: "004-221-118-000",
    city: "Cebu City, PH",
    cat: "Civil works",
    offers: ["Steel", "Fabrication"],
    active: true,
    bankPending: false,
  },
  {
    code: "JCE 00021",
    name: "JinkoSolar Intl.",
    top: "LC",
    tin: "—",
    city: "Shanghai, CN",
    cat: "Electrical equipment",
    offers: ["PV modules"],
    active: true,
    bankPending: false,
  },
  {
    code: "JCE 00003",
    name: "ABB Inc.",
    top: "NET30",
    tin: "002-118-552-000",
    city: "Makati, PH",
    cat: "Electrical equipment",
    offers: ["Relays", "Breakers"],
    active: true,
    bankPending: false,
  },
  {
    code: "JCE 00009",
    name: "Meralco Industrial",
    top: "NET15",
    tin: "000-333-444-000",
    city: "Pasig, PH",
    cat: "Electrical equipment",
    offers: ["Conductors"],
    active: true,
    bankPending: false,
  },
];

// ---- U11 Purchase Requisitions --------------------------------------------
const PRQS = [
  {
    no: "PRQ-26-0210",
    date: "2026-06-02",
    requestor: "PMG Staff",
    project: "Workshop",
    mr: "—",
    est: 48200,
    ccy: "PHP",
    urgency: "Routine",
    status: "Pending Approval",
    step: "Supervisor",
  },
  {
    no: "PRQ-26-0205",
    date: "2026-05-28",
    requestor: "N. Aquino",
    project: "NORECO II — 13.2KV",
    mr: "JCE-MR-2026-0142",
    est: 4200000,
    ccy: "PHP",
    urgency: "Critical",
    status: "Approved",
    step: "—",
  },
  {
    no: "PRQ-26-0198",
    date: "2026-05-20",
    requestor: "PMG Staff",
    project: "Cavite 69KV",
    mr: "JCE-MR-2026-0140",
    est: 1240000,
    ccy: "PHP",
    urgency: "Urgent",
    status: "Converted to PO",
    step: "—",
  },
];
const URGENCY_TONE = {
  Routine: "neutral",
  Urgent: "pending",
  Critical: "danger",
};
const PRQ_TONE = {
  Draft: "neutral",
  "Pending Approval": "pending",
  Approved: "success",
  Rejected: "danger",
  "Converted to PO": "info",
  Cancelled: "neutral",
};

// ---- U12 approval queue (cross-entity) ------------------------------------
const APPROVALS = [
  {
    entity: "Import stage 7",
    ref: "2605-0188IC",
    payee: "Shenda Electric Co.",
    amount: 1764000,
    ccy: "PHP",
    requestor: "Purchasing",
    age: "2d",
    urgency: "Critical",
    note: "Downpayment release gate",
  },
  {
    entity: "PO",
    ref: "2606-0210",
    payee: "Cebu Steel Corp.",
    amount: 48200,
    ccy: "PHP",
    requestor: "PMG Staff",
    age: "6h",
    urgency: "Routine",
    note: "For Approval — welding consumables",
  },
  {
    entity: "PR",
    ref: "PRQ-26-0210",
    payee: "—",
    amount: 48200,
    ccy: "PHP",
    requestor: "PMG Staff",
    age: "1d",
    urgency: "Routine",
    note: "Pre-PO budget authorization",
  },
  {
    entity: "RFP",
    ref: "RFP-PUR-26050188",
    payee: "Cebu Steel Corp.",
    amount: 312081,
    ccy: "PHP",
    requestor: "Purchasing",
    age: "4h",
    urgency: "Urgent",
    note: "Single payment — verified",
  },
];
const ENTITY_TONE = {
  PO: "info",
  PR: "neutral",
  RFP: "success",
  Blanket: "pending",
  "Import stage 7": "danger",
  "Import stage 4": "danger",
};

// ---- U13 audit -------------------------------------------------------------
const PUR_AUDIT = [
  {
    ts: "2026-06-02 11:20",
    actor: "N. Aquino (Supervisor)",
    entity: "2606-0210",
    action: "PO submit",
    delta: "Draft → For Approval",
  },
  {
    ts: "2026-06-02 09:05",
    actor: "Purchasing Staff",
    entity: "RFP-PUR-26060021",
    action: "RFP create",
    delta: "— → Submitted (DP)",
  },
  {
    ts: "2026-05-23 16:40",
    actor: "J. Cruz (President)",
    entity: "2605-0188IC",
    action: "Import gate 4 approve",
    delta: "Pending → Done",
  },
  {
    ts: "2026-05-22 10:00",
    actor: "N. Aquino (Supervisor)",
    entity: "Shenda Electric Co.",
    action: "Supplier bank change",
    delta: "Pending verification (fraud-control)",
  },
];

const pmoneyU = (n) =>
  n.toLocaleString("en-PH", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
const ccyAmt = (n, c) =>
  (c === "USD" ? "$" : "₱") + pmoneyU(n) + (c === "USD" ? " USD" : "");

Object.assign(window, {
  POS,
  PO_STATUS_TONE,
  PAY_TONE,
  IMPORT_STAGES,
  STAGE_TONE,
  RFPS,
  RFP_TONE,
  SUPPLIERS,
  PRQS,
  URGENCY_TONE,
  PRQ_TONE,
  APPROVALS,
  ENTITY_TONE,
  PUR_AUDIT,
  pmoneyU,
  ccyAmt,
});
